/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : CourseId,
  'title' : string,
  'difficulty' : { 'intermediate' : null } |
    { 'beginner' : null } |
    { 'advanced' : null },
  'description' : string,
  'lessons' : Array<Lesson>,
}
export type CourseId = bigint;
export interface Lesson {
  'id' : LessonId,
  'title' : string,
  'content' : string,
}
export type LessonId = bigint;
export interface UserProgress {
  'completedLessons' : Array<[CourseId, Array<LessonId>]>,
  'enrolledCourses' : Array<CourseId>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminAddCourse' : ActorMethod<
    [
      string,
      string,
      { 'intermediate' : null } |
        { 'beginner' : null } |
        { 'advanced' : null },
    ],
    CourseId
  >,
  'adminAddLesson' : ActorMethod<[CourseId, string, string], LessonId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'browseCourses' : ActorMethod<[], Array<Course>>,
  'completeLesson' : ActorMethod<[CourseId, LessonId], undefined>,
  'enrollInCourse' : ActorMethod<[CourseId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[CourseId], Course>,
  'getCourseProgress' : ActorMethod<
    [CourseId],
    { 'totalLessons' : bigint, 'completedLessons' : bigint }
  >,
  'getUserProgress' : ActorMethod<[Principal], UserProgress>,
  'init' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'searchCourses' : ActorMethod<[string], Array<Course>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];