/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CourseId = IDL.Nat;
export const LessonId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Lesson = IDL.Record({
  'id' : LessonId,
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : CourseId,
  'title' : IDL.Text,
  'difficulty' : IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  }),
  'description' : IDL.Text,
  'lessons' : IDL.Vec(Lesson),
});
export const UserProgress = IDL.Record({
  'completedLessons' : IDL.Vec(IDL.Tuple(CourseId, IDL.Vec(LessonId))),
  'enrolledCourses' : IDL.Vec(CourseId),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminAddCourse' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'intermediate' : IDL.Null,
          'beginner' : IDL.Null,
          'advanced' : IDL.Null,
        }),
      ],
      [CourseId],
      [],
    ),
  'adminAddLesson' : IDL.Func([CourseId, IDL.Text, IDL.Text], [LessonId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'browseCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'completeLesson' : IDL.Func([CourseId, LessonId], [], []),
  'enrollInCourse' : IDL.Func([CourseId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([CourseId], [Course], ['query']),
  'getCourseProgress' : IDL.Func(
      [CourseId],
      [IDL.Record({ 'totalLessons' : IDL.Nat, 'completedLessons' : IDL.Nat })],
      ['query'],
    ),
  'getUserProgress' : IDL.Func([IDL.Principal], [UserProgress], ['query']),
  'init' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'searchCourses' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CourseId = IDL.Nat;
  const LessonId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Lesson = IDL.Record({
    'id' : LessonId,
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : CourseId,
    'title' : IDL.Text,
    'difficulty' : IDL.Variant({
      'intermediate' : IDL.Null,
      'beginner' : IDL.Null,
      'advanced' : IDL.Null,
    }),
    'description' : IDL.Text,
    'lessons' : IDL.Vec(Lesson),
  });
  const UserProgress = IDL.Record({
    'completedLessons' : IDL.Vec(IDL.Tuple(CourseId, IDL.Vec(LessonId))),
    'enrolledCourses' : IDL.Vec(CourseId),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminAddCourse' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'intermediate' : IDL.Null,
            'beginner' : IDL.Null,
            'advanced' : IDL.Null,
          }),
        ],
        [CourseId],
        [],
      ),
    'adminAddLesson' : IDL.Func([CourseId, IDL.Text, IDL.Text], [LessonId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'browseCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'completeLesson' : IDL.Func([CourseId, LessonId], [], []),
    'enrollInCourse' : IDL.Func([CourseId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([CourseId], [Course], ['query']),
    'getCourseProgress' : IDL.Func(
        [CourseId],
        [
          IDL.Record({
            'totalLessons' : IDL.Nat,
            'completedLessons' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProgress' : IDL.Func([IDL.Principal], [UserProgress], ['query']),
    'init' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'searchCourses' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };